### ISSUE TITLE
Copy-Paste isn't working on Mac

### ISSUE THREAD

**Issue by csaunders** [lonnc/golang-nw#17] opened 2015-02-27 21:39 UTC
Looks like this can be fixed by improvements to the client `script.js` though I'm not super sure. Also I think there might be something broken on the later versions of nwjs.

Here's some of the related issues:

- https://github.com/nwjs/nw.js/issues/1955
- https://github.com/nwjs/nw.js/issues/2039

**Comment by tommoor** [comment] 2015-03-01 22:18
Confirmed regressions in the 0.12 releases

**Comment by girishso** [comment] 2015-07-10 10:46
Copy-paste does not work in Mac since the `Edit` menu is disabled by default. Resolved in PR https://github.com/lonnc/golang-nw/pull/19

**Closed** 2015-07-10 11:41 UTC
